/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#FF6B9A',
          50: '#FFF0F5',
          100: '#FFE6F0',
          200: '#FFCCE0',
          300: '#FFB3D1',
          400: '#FF8FB5',
          500: '#FF6B9A',
          600: '#FF3D7A',
          700: '#FF0F5A',
          800: '#D6003D',
          900: '#A30030',
        },
        secondary: {
          DEFAULT: '#B7DCEF',
          50: '#F0F8FC',
          100: '#E1F1FA',
          200: '#C3E4F5',
          300: '#B7DCEF',
          400: '#8DC9E6',
          500: '#63B5DD',
          600: '#3AA1D4',
          700: '#2E81AA',
          800: '#236180',
          900: '#184056',
        },
        lavender: {
          DEFAULT: '#DCC6FF',
          50: '#FAF5FF',
          100: '#F3EBFF',
          200: '#E8D9FF',
          300: '#DCC6FF',
          400: '#C7A3FF',
          500: '#B280FF',
          600: '#9D5CFF',
          700: '#8839FF',
          800: '#6B0FFF',
          900: '#5300D6',
        },
        background: '#FAFCFF',
        card: '#FFFFFF',
        'light-gray': '#F6F7FB',
        'text-primary': '#1E293B',
        'text-secondary': '#64748B',
        success: '#10B981',
        warning: '#F59E0B',
        error: '#EF4444',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '20px',
        '3xl': '24px',
      },
      boxShadow: {
        'soft': '0 4px 20px rgba(0, 0, 0, 0.05)',
        'glow': '0 0 20px rgba(255, 107, 154, 0.15)',
        'card': '0 2px 12px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 8px 30px rgba(0, 0, 0, 0.08)',
        'glass': '0 8px 32px rgba(31, 38, 135, 0.07)',
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'float-slow': 'float 4s ease-in-out infinite',
        'bounce-soft': 'bounce-soft 2s ease-in-out infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'paw-step': 'paw-step 0.6s ease-out',
        'heart-beat': 'heart-beat 1.5s ease-in-out infinite',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.4s ease-out',
        'scale-in': 'scale-in 0.3s ease-out',
        'tail-wag': 'tail-wag 0.8s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'bounce-soft': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'paw-step': {
          '0%': { opacity: '0', transform: 'scale(0.5) rotate(-20deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
        },
        'heart-beat': {
          '0%, 100%': { transform: 'scale(1)' },
          '25%': { transform: 'scale(1.1)' },
          '50%': { transform: 'scale(1)' },
          '75%': { transform: 'scale(1.1)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'tail-wag': {
          '0%, 100%': { transform: 'rotate(-10deg)' },
          '50%': { transform: 'rotate(10deg)' },
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
